version: '3.8'

services:
  db:
    image: mariadb:10.4
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: dotinnc_wp
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.1-apache
    container_name: wp_app
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: dotinnc_wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_pma
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""

volumes:
  db_data:
